name: thomas
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  audioplayers: ^5.2.0
  flame: ^1.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/ui/component/images/
    - assets/
    - assets/wide.mp4
